apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync-emco
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/iwojdan/test-Anthos.git
    revision: HEAD
    branch: main
    dir: "/clusters/provider-anthos17+cluster27"
    auth: none
    noSSLVerify: false
