{"apiVersion":"v1","data":{"REACT_APP_PASSWORD":"changeMe"},"kind":"ConfigMap","metadata":{"labels":{"emco/deployment-id":"3139354211276721287-wef-5-0"},"name":"r1-ue-mngmt-tool-env-cfgmap","namespace":"default"}}
