{"apiVersion":"v1","data":{"AMF_INSTANCE_ID":"edfb2480-8953-45d4-8e6b-006e26f0e9aa"},"kind":"ConfigMap","metadata":{"labels":{"emco/deployment-id":"1687519632397923676-wef-5-0"},"name":"r1-nfinstanceid-config","namespace":"default"}}
